### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by thiagodp** [AnyhowStep/enum-util#1]
First of all, thanks for this useful library.

I would like to suggest the release of project versions as tags (e.g., ~~`npm tag v1.1.0 -m "Refactored for type-safety" && npm push --tags`~~ `git tag v1.1.0 -m "Refactored for type-safety" && git push --tags`).

thx!

**Comment by AnyhowStep** [comment]
I'm glad you found it useful!

I must confess I've never used npm tags before. I'm not sure what a good tag name is but I don't think I've ever seen a tag name more than one or two words like "alpha", "beta", "next".

**Comment by thiagodp** [comment]
Sorry, where you read `npm` please read `git`. So `git tag v1.1.0 -m "Refactored for type-safety" && git push --tags`. I think I'd mistaken that because I'm used to use [npm version](https://docs.npmjs.com/cli/version) instead of `git tag`, then use `git push --tags`.

Tag *names* could follow [semantic versioning](https://semver.org/), such as `v1.1.0`, while their *descriptions* could indicate improvements made, such as `Refactored for type-safety`.

**Comment by AnyhowStep** [comment]
Thanks for taking the time to explain it to me! I decided to go with `1.1.0` instead.

**Comment by thiagodp** [comment]
You're welcome! Thanks for [releasing v1.1.0](https://github.com/AnyhowStep/enum-util/releases/tag/1.1.0).
